### ISSUE TITLE
Without a visual diagram, what other configuration is required

### ISSUE THREAD

**Issue by hcj131518** [UofS-Pulse-Binfo/cvitembed#6]
Click, no figure 2 result appears, what other configuration is required
![e7be91c42a3855dd18b09f4a8a45c83](https://user-images.githubusercontent.com/85207013/187840856-2647d804-857a-462f-8b2f-aa60f0587d74.jpg)
![image](https://user-images.githubusercontent.com/85207013/187841100-09a55c01-ee8f-4e5b-a484-ace28d89451b.png)

**Comment by laceysanderson** [comment]
Hello, I am not sure what you mean? It looks like you have the module installed correctly. It's a really simple module and doesn't need any configuration per se.

The only thing left to do is add your own diagrams. This is done by following the information provided by the cvitjs library. Then once you get your diagram created, you get it to show up in the Tripal site using this module by following the tips + tricks on the readme.

**Comment by hcj131518** [comment]
Thank you for your reply. Now the problem has been solved.Just visualizations load slowly.



---Original---
From: "Lacey-Anne ***@***.***&gt;
Date: Fri, Sep 2, 2022 22:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [UofS-Pulse-Binfo/cvitembed] Without a visual diagram, what otherconfiguration is required (Issue #6)




 
Hello, I am not sure what you mean? It looks like you have the module installed correctly. It's a really simple module and doesn't need any configuration per se.
 
The only thing left to do is add your own diagrams. This is done by following the information provided by the cvitjs library. Then once you get your diagram created, you get it to show up in the Tripal site using this module by following the tips + tricks on the readme.

**Comment by laceysanderson** [comment]
Yes we found that as well. It's a problem with the CVitjs library as it expects you to have pre-filtered your dataset ahead if time...
